apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul
  namespace: consul-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
        - name: consul
          image: consul:1.15
          ports:
            - containerPort: 8500
              name: http
            - containerPort: 8600
              name: dns
              protocol: UDP
          args: ["agent", "-server", "-bootstrap", "-ui", "-client=0.0.0.0"]
---
apiVersion: v1
kind: Service
metadata:
  name: consul
  namespace: consul-demo
spec:
  selector:
    app: consul
  ports:
    - name: http
      port: 8500
      targetPort: 8500
    - name: dns
      port: 8600
      targetPort: 8600
      protocol: UDP
